# Generated by Django 4.2.5 on 2023-09-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_items_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='items',
            name='item',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
